# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/danielsinclair/vscode/engine-sim-cli

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/danielsinclair/vscode/engine-sim-cli

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/danielsinclair/vscode/engine-sim-cli/CMakeFiles /Users/danielsinclair/vscode/engine-sim-cli//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/danielsinclair/vscode/engine-sim-cli/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named engine-sim-mock

# Build rule for target.
engine-sim-mock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine-sim-mock
.PHONY : engine-sim-mock

# fast build rule for target.
engine-sim-mock/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-mock.dir/build.make CMakeFiles/engine-sim-mock.dir/build
.PHONY : engine-sim-mock/fast

#=============================================================================
# Target rules for targets named sine-wave-generator

# Build rule for target.
sine-wave-generator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sine-wave-generator
.PHONY : sine-wave-generator

# fast build rule for target.
sine-wave-generator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sine-wave-generator.dir/build.make CMakeFiles/sine-wave-generator.dir/build
.PHONY : sine-wave-generator/fast

#=============================================================================
# Target rules for targets named engine-sim-cli

# Build rule for target.
engine-sim-cli: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine-sim-cli
.PHONY : engine-sim-cli

# fast build rule for target.
engine-sim-cli/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/build
.PHONY : engine-sim-cli/fast

#=============================================================================
# Target rules for targets named engine-sim-bridge

# Build rule for target.
engine-sim-bridge: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine-sim-bridge
.PHONY : engine-sim-bridge

# fast build rule for target.
engine-sim-bridge/fast:
	$(MAKE) $(MAKESILENT) -f engine-sim-bridge/CMakeFiles/engine-sim-bridge.dir/build.make engine-sim-bridge/CMakeFiles/engine-sim-bridge.dir/build
.PHONY : engine-sim-bridge/fast

#=============================================================================
# Target rules for targets named engine-sim

# Build rule for target.
engine-sim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine-sim
.PHONY : engine-sim

# fast build rule for target.
engine-sim/fast:
	$(MAKE) $(MAKESILENT) -f engine-sim/CMakeFiles/engine-sim.dir/build.make engine-sim/CMakeFiles/engine-sim.dir/build
.PHONY : engine-sim/fast

#=============================================================================
# Target rules for targets named engine-sim-script-interpreter

# Build rule for target.
engine-sim-script-interpreter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine-sim-script-interpreter
.PHONY : engine-sim-script-interpreter

# fast build rule for target.
engine-sim-script-interpreter/fast:
	$(MAKE) $(MAKESILENT) -f engine-sim/CMakeFiles/engine-sim-script-interpreter.dir/build.make engine-sim/CMakeFiles/engine-sim-script-interpreter.dir/build
.PHONY : engine-sim-script-interpreter/fast

#=============================================================================
# Target rules for targets named engine-sim-app

# Build rule for target.
engine-sim-app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine-sim-app
.PHONY : engine-sim-app

# fast build rule for target.
engine-sim-app/fast:
	$(MAKE) $(MAKESILENT) -f engine-sim/CMakeFiles/engine-sim-app.dir/build.make engine-sim/CMakeFiles/engine-sim-app.dir/build
.PHONY : engine-sim-app/fast

#=============================================================================
# Target rules for targets named engine-sim-test

# Build rule for target.
engine-sim-test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine-sim-test
.PHONY : engine-sim-test

# fast build rule for target.
engine-sim-test/fast:
	$(MAKE) $(MAKESILENT) -f engine-sim/CMakeFiles/engine-sim-test.dir/build.make engine-sim/CMakeFiles/engine-sim-test.dir/build
.PHONY : engine-sim-test/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named simple-2d-constraint-solver

# Build rule for target.
simple-2d-constraint-solver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simple-2d-constraint-solver
.PHONY : simple-2d-constraint-solver

# fast build rule for target.
simple-2d-constraint-solver/fast:
	$(MAKE) $(MAKESILENT) -f engine-sim/dependencies/submodules/simple-2d-constraint-solver/CMakeFiles/simple-2d-constraint-solver.dir/build.make engine-sim/dependencies/submodules/simple-2d-constraint-solver/CMakeFiles/simple-2d-constraint-solver.dir/build
.PHONY : simple-2d-constraint-solver/fast

#=============================================================================
# Target rules for targets named simple-2d-constraint-solver-test

# Build rule for target.
simple-2d-constraint-solver-test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simple-2d-constraint-solver-test
.PHONY : simple-2d-constraint-solver-test

# fast build rule for target.
simple-2d-constraint-solver-test/fast:
	$(MAKE) $(MAKESILENT) -f engine-sim/dependencies/submodules/simple-2d-constraint-solver/CMakeFiles/simple-2d-constraint-solver-test.dir/build.make engine-sim/dependencies/submodules/simple-2d-constraint-solver/CMakeFiles/simple-2d-constraint-solver-test.dir/build
.PHONY : simple-2d-constraint-solver-test/fast

#=============================================================================
# Target rules for targets named csv-io

# Build rule for target.
csv-io: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 csv-io
.PHONY : csv-io

# fast build rule for target.
csv-io/fast:
	$(MAKE) $(MAKESILENT) -f engine-sim/dependencies/submodules/csv-io/CMakeFiles/csv-io.dir/build.make engine-sim/dependencies/submodules/csv-io/CMakeFiles/csv-io.dir/build
.PHONY : csv-io/fast

#=============================================================================
# Target rules for targets named csv-io-main

# Build rule for target.
csv-io-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 csv-io-main
.PHONY : csv-io-main

# fast build rule for target.
csv-io-main/fast:
	$(MAKE) $(MAKESILENT) -f engine-sim/dependencies/submodules/csv-io/CMakeFiles/csv-io-main.dir/build.make engine-sim/dependencies/submodules/csv-io/CMakeFiles/csv-io-main.dir/build
.PHONY : csv-io-main/fast

#=============================================================================
# Target rules for targets named csv-io-test

# Build rule for target.
csv-io-test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 csv-io-test
.PHONY : csv-io-test

# fast build rule for target.
csv-io-test/fast:
	$(MAKE) $(MAKESILENT) -f engine-sim/dependencies/submodules/csv-io/CMakeFiles/csv-io-test.dir/build.make engine-sim/dependencies/submodules/csv-io/CMakeFiles/csv-io-test.dir/build
.PHONY : csv-io-test/fast

#=============================================================================
# Target rules for targets named piranha

# Build rule for target.
piranha: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 piranha
.PHONY : piranha

# fast build rule for target.
piranha/fast:
	$(MAKE) $(MAKESILENT) -f engine-sim/dependencies/submodules/piranha/CMakeFiles/piranha.dir/build.make engine-sim/dependencies/submodules/piranha/CMakeFiles/piranha.dir/build
.PHONY : piranha/fast

#=============================================================================
# Target rules for targets named piranha_reference_compiler

# Build rule for target.
piranha_reference_compiler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 piranha_reference_compiler
.PHONY : piranha_reference_compiler

# fast build rule for target.
piranha_reference_compiler/fast:
	$(MAKE) $(MAKESILENT) -f engine-sim/dependencies/submodules/piranha/CMakeFiles/piranha_reference_compiler.dir/build.make engine-sim/dependencies/submodules/piranha/CMakeFiles/piranha_reference_compiler.dir/build
.PHONY : piranha_reference_compiler/fast

#=============================================================================
# Target rules for targets named piranha_test

# Build rule for target.
piranha_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 piranha_test
.PHONY : piranha_test

# fast build rule for target.
piranha_test/fast:
	$(MAKE) $(MAKESILENT) -f engine-sim/dependencies/submodules/piranha/CMakeFiles/piranha_test.dir/build.make engine-sim/dependencies/submodules/piranha/CMakeFiles/piranha_test.dir/build
.PHONY : piranha_test/fast

engine-sim-bridge/src/mock_engine_sim.o: engine-sim-bridge/src/mock_engine_sim.cpp.o
.PHONY : engine-sim-bridge/src/mock_engine_sim.o

# target to build an object file
engine-sim-bridge/src/mock_engine_sim.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-mock.dir/build.make CMakeFiles/engine-sim-mock.dir/engine-sim-bridge/src/mock_engine_sim.cpp.o
.PHONY : engine-sim-bridge/src/mock_engine_sim.cpp.o

engine-sim-bridge/src/mock_engine_sim.i: engine-sim-bridge/src/mock_engine_sim.cpp.i
.PHONY : engine-sim-bridge/src/mock_engine_sim.i

# target to preprocess a source file
engine-sim-bridge/src/mock_engine_sim.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-mock.dir/build.make CMakeFiles/engine-sim-mock.dir/engine-sim-bridge/src/mock_engine_sim.cpp.i
.PHONY : engine-sim-bridge/src/mock_engine_sim.cpp.i

engine-sim-bridge/src/mock_engine_sim.s: engine-sim-bridge/src/mock_engine_sim.cpp.s
.PHONY : engine-sim-bridge/src/mock_engine_sim.s

# target to generate assembly for a file
engine-sim-bridge/src/mock_engine_sim.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-mock.dir/build.make CMakeFiles/engine-sim-mock.dir/engine-sim-bridge/src/mock_engine_sim.cpp.s
.PHONY : engine-sim-bridge/src/mock_engine_sim.cpp.s

src/engine_sim_cli.o: src/engine_sim_cli.cpp.o
.PHONY : src/engine_sim_cli.o

# target to build an object file
src/engine_sim_cli.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/engine_sim_cli.cpp.o
.PHONY : src/engine_sim_cli.cpp.o

src/engine_sim_cli.i: src/engine_sim_cli.cpp.i
.PHONY : src/engine_sim_cli.i

# target to preprocess a source file
src/engine_sim_cli.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/engine_sim_cli.cpp.i
.PHONY : src/engine_sim_cli.cpp.i

src/engine_sim_cli.s: src/engine_sim_cli.cpp.s
.PHONY : src/engine_sim_cli.s

# target to generate assembly for a file
src/engine_sim_cli.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/engine_sim_cli.cpp.s
.PHONY : src/engine_sim_cli.cpp.s

src/sine_wave_generator.o: src/sine_wave_generator.cpp.o
.PHONY : src/sine_wave_generator.o

# target to build an object file
src/sine_wave_generator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sine-wave-generator.dir/build.make CMakeFiles/sine-wave-generator.dir/src/sine_wave_generator.cpp.o
.PHONY : src/sine_wave_generator.cpp.o

src/sine_wave_generator.i: src/sine_wave_generator.cpp.i
.PHONY : src/sine_wave_generator.i

# target to preprocess a source file
src/sine_wave_generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sine-wave-generator.dir/build.make CMakeFiles/sine-wave-generator.dir/src/sine_wave_generator.cpp.i
.PHONY : src/sine_wave_generator.cpp.i

src/sine_wave_generator.s: src/sine_wave_generator.cpp.s
.PHONY : src/sine_wave_generator.s

# target to generate assembly for a file
src/sine_wave_generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sine-wave-generator.dir/build.make CMakeFiles/sine-wave-generator.dir/src/sine_wave_generator.cpp.s
.PHONY : src/sine_wave_generator.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... csv-io"
	@echo "... csv-io-main"
	@echo "... csv-io-test"
	@echo "... engine-sim"
	@echo "... engine-sim-app"
	@echo "... engine-sim-bridge"
	@echo "... engine-sim-cli"
	@echo "... engine-sim-mock"
	@echo "... engine-sim-script-interpreter"
	@echo "... engine-sim-test"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... piranha"
	@echo "... piranha_reference_compiler"
	@echo "... piranha_test"
	@echo "... simple-2d-constraint-solver"
	@echo "... simple-2d-constraint-solver-test"
	@echo "... sine-wave-generator"
	@echo "... engine-sim-bridge/src/mock_engine_sim.o"
	@echo "... engine-sim-bridge/src/mock_engine_sim.i"
	@echo "... engine-sim-bridge/src/mock_engine_sim.s"
	@echo "... src/engine_sim_cli.o"
	@echo "... src/engine_sim_cli.i"
	@echo "... src/engine_sim_cli.s"
	@echo "... src/sine_wave_generator.o"
	@echo "... src/sine_wave_generator.i"
	@echo "... src/sine_wave_generator.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

