sonar.projectKey=danieljsinclair_engine-sim-cli
sonar.projectName=engine-sim-cli
sonar.sources=src
sonar.tests=test
sonar.sourceEncoding=UTF-8
sonar.cfamily.compile-commands=build-cov/compile_commands.json
sonar.host.url=https://sonarcloud.io
sonar.organization=danieljsinclair
sonar.exclusions=engine-sim-bridge/**,engine-sim-esp32/**,engine-sim-tui/**,build/**,build-cov/**,es/**,escli-ios/**,vehicle-sim/**,scripts/**,_deps/**
sonar.coverage.exclusions=test/**,engine-sim-bridge/**,engine-sim-esp32/**,tools/**,scripts/**
sonar.cfamily.threads=4
sonar.sourceVersion=17
sonar.cfamily.coverage.reportPaths=build-cov/coverage.txt
