// SyncPullAudioMode.cpp - Sync-pull audio mode implementation
// DI: Creates and injects SyncPullRenderer into context

#include "audio/modes/SyncPullAudioMode.h"
#include "audio/modes/IAudioMode.h"
#include "SimulationLoop.h"
#include "AudioPlayer.h"
#include "AudioSource.h"
#include "CircularBuffer.h"
#include "SyncPullAudio.h"

#include "audio/renderers/SyncPullRenderer.h"

#include <iostream>

void SyncPullAudioMode::configure(const SimulationConfig& config) {
    preFillMs_ = config.preFillMs;
}

std::string SyncPullAudioMode::getModeName() const {
    return "SyncPull";
}

void SyncPullAudioMode::updateSimulation(EngineSimHandle handle, const EngineSimAPI& api,
                                          AudioPlayer* audioPlayer) {
    // Sync-pull mode: simulation is NOT updated here
    // It's updated by the audio callback instead
    (void)handle;
    (void)api;
    (void)audioPlayer;
}

void SyncPullAudioMode::generateAudio(IAudioSource& audioSource, AudioPlayer* audioPlayer) {
    // Sync-pull mode: audio is generated by the callback, not here
    (void)audioSource;
    (void)audioPlayer;
}

std::string SyncPullAudioMode::getModeString() const {
    return "sync-pull";
}

bool SyncPullAudioMode::startAudioThread(EngineSimHandle handle, const EngineSimAPI& api,
                                          AudioPlayer* audioPlayer) {
    // Sync-pull mode: no separate audio thread
    (void)handle;
    (void)api;
    (void)audioPlayer;
    return true;
}

void SyncPullAudioMode::prepareBuffer(AudioPlayer* audioPlayer) {
    // Sync-pull mode: no buffer preparation needed (done in resetBufferAfterWarmup)
    if (syncPullAudio_) {
        syncPullAudio_->preFillBuffer(preFillMs_);
    }
    (void)audioPlayer;
}

void SyncPullAudioMode::resetBufferAfterWarmup(AudioPlayer* audioPlayer) {
    // Sync-pull mode: no buffer reset needed
    (void)audioPlayer;
}

void SyncPullAudioMode::startPlayback(AudioPlayer* audioPlayer) {
    if (audioPlayer) {
        audioPlayer->start();
        std::cout << "[Audio playback enabled]\n";
    }
}

bool SyncPullAudioMode::shouldDrainDuringWarmup() const {
    // Sync-pull mode: no draining during warmup
    return false;
}

std::unique_ptr<AudioUnitContext> SyncPullAudioMode::createContext(
    int sampleRate,
    EngineSimHandle engineHandle,
    const EngineSimAPI* engineAPI
) {
    auto context = std::make_unique<AudioUnitContext>();
    context->sampleRate = sampleRate;
    context->engineHandle = engineHandle;

    // Create SyncPullAudio for synchronous on-demand rendering
    context->syncPullAudio = std::make_unique<SyncPullAudio>();
    if (!context->syncPullAudio->initialize(engineHandle, engineAPI, sampleRate)) {
        std::cerr << "ERROR: Failed to initialize SyncPullAudio\n";
        return nullptr;
    }
    context->syncPullAudio->setContext(context.get());  // Set context for pre-buffer tracking
    syncPullAudio_ = context->syncPullAudio.get();  // Store raw pointer for prepareBuffer

    // DI: Inject SyncPullRenderer into context (mode knows its own renderer)
    // This eliminates conditional branching in AudioPlayer
    static SyncPullRenderer syncPullRenderer;
    context->setRenderer(&syncPullRenderer);

    std::cout << "[Audio] Sync pull mode initialized via factory\n";
    return context;
}
