#!/bin/bash
# Test script for interactive controls
# This simulates key presses to test the fixes

echo "Testing Interactive Control Fixes"
echo "=================================="
echo ""
echo "This test requires manual interaction. Please run:"
echo "  cd /Users/danielsinclair/vscode/engine-sim-cli/build"
echo "  ./engine-sim-cli --default-engine --interactive --play"
echo ""
echo "Test Plan:"
echo "1. W Key Test:"
echo "   - Press and hold W"
echo "   - Throttle should increase (shown in HUD)"
echo "   - Release W"
echo "   - Throttle should gradually decay back to baseline"
echo ""
echo "2. J/K Keys Test:"
echo "   - Press J multiple times"
echo "   - Throttle should decrease each time"
echo "   - Press K multiple times"
echo "   - Throttle should increase each time"
echo ""
echo "3. R Key Test:"
echo "   - Press R to reset"
echo "   - Throttle should set to 20% and stay stable"
echo "   - No pulsation should occur"
echo ""
echo "Expected Results:"
echo "  - W key: Temporary throttle boost that decays"
echo "  - J/K keys: Immediate throttle changes that persist"
echo "  - R key: Smooth reset to 20% throttle, no oscillation"
