if(EXISTS "/Users/danielsinclair/vscode/engine-sim-cli/engine-sim/dependencies/submodules/csv-io/csv-io-test[1]_tests.cmake")
  include("/Users/danielsinclair/vscode/engine-sim-cli/engine-sim/dependencies/submodules/csv-io/csv-io-test[1]_tests.cmake")
else()
  add_test(csv-io-test_NOT_BUILT csv-io-test_NOT_BUILT)
endif()
