// AudioMode.cpp - Strategy pattern implementation for audio modes
// Renderer is injected into context by each mode (OCP, SRP, DI)

#include "AudioMode.h"
#include "AudioPlayer.h"
#include "AudioSource.h"
#include "CircularBuffer.h"
#include "SyncPullAudio.h"

#include <iostream>

// ============================================================================
// AudioLoopConfig - Constants for audio loop timing
// ============================================================================

namespace AudioLoopConfig {
    constexpr double UPDATE_INTERVAL = 1.0 / 60.0;  // 60 Hz update rate
    constexpr int SAMPLE_RATE = 44100;
    constexpr int FRAMES_PER_UPDATE = 735;  // 44100 / 60
}

// ============================================================================
// SyncPullAudioMode Implementation
// DI: Creates and injects SyncPullRenderer into context
// ============================================================================

std::string SyncPullAudioMode::getModeName() const {
    return "SyncPull";
}

void SyncPullAudioMode::updateSimulation(EngineSimHandle handle, const EngineSimAPI& api,
                                          AudioPlayer* audioPlayer) {
    // Sync-pull mode: simulation is NOT updated here
    // It's updated by the audio callback instead
    (void)handle;
    (void)api;
    (void)audioPlayer;
}

void SyncPullAudioMode::generateAudio(IAudioSource& audioSource, AudioPlayer* audioPlayer) {
    // Sync-pull mode: audio is generated by the callback, not here
    (void)audioSource;
    (void)audioPlayer;
}

std::string SyncPullAudioMode::getModeString() const {
    return "sync-pull";
}

bool SyncPullAudioMode::startAudioThread(EngineSimHandle handle, const EngineSimAPI& api,
                                          AudioPlayer* audioPlayer) {
    // Sync-pull mode: no separate audio thread
    (void)handle;
    (void)api;
    (void)audioPlayer;
    return true;
}

void SyncPullAudioMode::prepareBuffer(AudioPlayer* audioPlayer) {
    // Sync-pull mode: no buffer preparation needed
    (void)audioPlayer;
}

void SyncPullAudioMode::resetBufferAfterWarmup(AudioPlayer* audioPlayer) {
    // Sync-pull mode: no buffer reset needed
    (void)audioPlayer;
}

void SyncPullAudioMode::startPlayback(AudioPlayer* audioPlayer) {
    if (audioPlayer) {
        audioPlayer->start();
        std::cout << "[Audio playback enabled]\n";
    }
}

bool SyncPullAudioMode::shouldDrainDuringWarmup() const {
    // Sync-pull mode: no draining during warmup
    return false;
}

std::unique_ptr<AudioUnitContext> SyncPullAudioMode::createContext(
    int sampleRate,
    EngineSimHandle engineHandle,
    const EngineSimAPI* engineAPI,
    bool silent
) {
    auto context = std::make_unique<AudioUnitContext>();
    context->sampleRate = sampleRate;
    context->silent = silent;
    context->engineHandle = engineHandle;

    // Create SyncPullAudio for synchronous on-demand rendering
    context->syncPullAudio = std::make_unique<SyncPullAudio>();
    if (!context->syncPullAudio->initialize(engineHandle, engineAPI, sampleRate, silent)) {
        std::cerr << "ERROR: Failed to initialize SyncPullAudio\n";
        return nullptr;
    }

    // DI: Inject SyncPullRenderer into context (mode knows its own renderer)
    // This eliminates conditional branching in AudioPlayer
    static SyncPullRenderer syncPullRenderer;
    context->setRenderer(&syncPullRenderer);

    std::cout << "[Audio] Sync pull mode initialized via factory\n";
    return context;
}

// ============================================================================
// ThreadedAudioMode Implementation
// DI: Creates and injects CircularBufferRenderer into context
// ============================================================================

std::string ThreadedAudioMode::getModeName() const {
    return "Threaded";
}

void ThreadedAudioMode::updateSimulation(EngineSimHandle handle, const EngineSimAPI& api,
                                         AudioPlayer* audioPlayer) {
    // Threaded mode: simulation is updated in the main loop
    api.Update(handle, AudioLoopConfig::UPDATE_INTERVAL);
    (void)audioPlayer;
}

void ThreadedAudioMode::generateAudio(IAudioSource& audioSource, AudioPlayer* audioPlayer) {
    if (!audioPlayer) {
        return;
    }
    
    int framesToWrite = audioPlayer->calculateCursorChasingSamples(AudioLoopConfig::FRAMES_PER_UPDATE);
    if (framesToWrite <= 0) {
        return;
    }
    
    std::vector<float> audioBuffer(framesToWrite * 2);
    if (audioSource.generateAudio(audioBuffer, framesToWrite)) {
        audioPlayer->addToCircularBuffer(audioBuffer.data(), framesToWrite);
    }
}

std::string ThreadedAudioMode::getModeString() const {
    return "threaded";
}

bool ThreadedAudioMode::startAudioThread(EngineSimHandle handle, const EngineSimAPI& api,
                                         AudioPlayer* audioPlayer) {
    if (!audioPlayer) {
        return true;
    }
    
    EngineSimResult result = api.StartAudioThread(handle);
    if (result != ESIM_SUCCESS) {
        std::cerr << "ERROR: Failed to start audio thread\n";
        return false;
    }
    std::cout << "[Audio thread started (threaded mode)]\n";
    return true;
}

void ThreadedAudioMode::prepareBuffer(AudioPlayer* audioPlayer) {
    if (!audioPlayer) {
        return;
    }
    BufferOps::preFillCircularBuffer(audioPlayer);
    audioPlayer->start();
    std::cout << "[Audio playback enabled]\n";
}

void ThreadedAudioMode::resetBufferAfterWarmup(AudioPlayer* audioPlayer) {
    if (!audioPlayer) {
        return;
    }
    BufferOps::resetAndRePrefillBuffer(audioPlayer);
}

void ThreadedAudioMode::startPlayback(AudioPlayer* audioPlayer) {
    // Threaded mode: playback started in prepareBuffer
    (void)audioPlayer;
}

bool ThreadedAudioMode::shouldDrainDuringWarmup() const {
    // Threaded mode: draining needed during warmup
    return true;
}

std::unique_ptr<AudioUnitContext> ThreadedAudioMode::createContext(
    int sampleRate,
    EngineSimHandle engineHandle,
    const EngineSimAPI* engineAPI,
    bool silent
) {
    (void)engineHandle;
    (void)engineAPI;

    auto context = std::make_unique<AudioUnitContext>();
    context->sampleRate = sampleRate;
    context->silent = silent;

    // Create CircularBuffer for cursor-chasing mode
    context->circularBuffer = std::make_unique<CircularBuffer>();
    if (!context->circularBuffer->initialize(96000)) {
        std::cerr << "ERROR: Failed to initialize CircularBuffer\n";
        return nullptr;
    }

    // Initialize write pointer with 100ms pre-fill
    context->writePointer.store(static_cast<int>(sampleRate * 0.1));
    context->readPointer.store(0);
    context->totalFramesRead.store(0);

    // DI: Inject CircularBufferRenderer into context (mode knows its own renderer)
    // This eliminates conditional branching in AudioPlayer
    static CircularBufferRenderer circularBufferRenderer;
    context->setRenderer(&circularBufferRenderer);

    std::cout << "[Audio] Threaded/cursor-chasing mode initialized via factory\n";
    return context;
}

// ============================================================================
// Factory Function - Factory decides internally based on API capabilities
// Returns IAudioMode directly - no enum, no switch
// ============================================================================

std::unique_ptr<IAudioMode> createAudioModeFactory(const EngineSimAPI* engineAPI) {
    // Factory decides internally: check if StartAudioThread is available
    // If the API supports threading, use threaded mode for better performance
    // Otherwise, fall back to sync-pull mode
    if (engineAPI && engineAPI->StartAudioThread) {
        std::cout << "[Audio] Factory selected Threaded mode (StartAudioThread available)\n";
        return std::make_unique<ThreadedAudioMode>();
    }
    
    std::cout << "[Audio] Factory selected SyncPull mode (StartAudioThread not available)\n";
    return std::make_unique<SyncPullAudioMode>();
}
