// AudioMode.cpp - Strategy pattern implementation for audio modes

#include "AudioMode.h"
#include "AudioPlayer.h"
#include "AudioSource.h"

#include <iostream>

// ============================================================================
// AudioLoopConfig - Constants for audio loop timing
// ============================================================================

namespace AudioLoopConfig {
    constexpr double UPDATE_INTERVAL = 1.0 / 60.0;  // 60 Hz update rate
    constexpr int SAMPLE_RATE = 44100;
    constexpr int FRAMES_PER_UPDATE = 735;  // 44100 / 60
}

// ============================================================================
// SyncPullAudioMode Implementation
// ============================================================================

std::string SyncPullAudioMode::getModeName() const {
    return "SyncPull";
}

void SyncPullAudioMode::updateSimulation(EngineSimHandle handle, const EngineSimAPI& api,
                                          AudioPlayer* audioPlayer) {
    // Sync-pull mode: simulation is NOT updated here
    // It's updated by the audio callback instead
    (void)handle;
    (void)api;
    (void)audioPlayer;
}

void SyncPullAudioMode::generateAudio(IAudioSource& audioSource, AudioPlayer* audioPlayer) {
    // Sync-pull mode: audio is generated by the callback, not here
    (void)audioSource;
    (void)audioPlayer;
}

std::string SyncPullAudioMode::getModeString() const {
    return "sync-pull";
}

bool SyncPullAudioMode::startAudioThread(EngineSimHandle handle, const EngineSimAPI& api,
                                          AudioPlayer* audioPlayer) {
    // Sync-pull mode: no separate audio thread
    (void)handle;
    (void)api;
    (void)audioPlayer;
    return true;
}

void SyncPullAudioMode::prepareBuffer(AudioPlayer* audioPlayer) {
    // Sync-pull mode: no buffer preparation needed
    (void)audioPlayer;
}

void SyncPullAudioMode::resetBufferAfterWarmup(AudioPlayer* audioPlayer) {
    // Sync-pull mode: no buffer reset needed
    (void)audioPlayer;
}

void SyncPullAudioMode::startPlayback(AudioPlayer* audioPlayer) {
    if (audioPlayer) {
        audioPlayer->start();
        std::cout << "[Audio playback enabled]\n";
    }
}

bool SyncPullAudioMode::shouldDrainDuringWarmup() const {
    // Sync-pull mode: no draining during warmup
    return false;
}

// ============================================================================
// ThreadedAudioMode Implementation
// ============================================================================

std::string ThreadedAudioMode::getModeName() const {
    return "Threaded";
}

void ThreadedAudioMode::updateSimulation(EngineSimHandle handle, const EngineSimAPI& api,
                                         AudioPlayer* audioPlayer) {
    // Threaded mode: simulation is updated in the main loop
    api.Update(handle, AudioLoopConfig::UPDATE_INTERVAL);
    (void)audioPlayer;
}

void ThreadedAudioMode::generateAudio(IAudioSource& audioSource, AudioPlayer* audioPlayer) {
    if (!audioPlayer) {
        return;
    }
    
    int framesToWrite = audioPlayer->calculateCursorChasingSamples(AudioLoopConfig::FRAMES_PER_UPDATE);
    if (framesToWrite <= 0) {
        return;
    }
    
    std::vector<float> audioBuffer(framesToWrite * 2);
    if (audioSource.generateAudio(audioBuffer, framesToWrite)) {
        audioPlayer->addToCircularBuffer(audioBuffer.data(), framesToWrite);
    }
}

std::string ThreadedAudioMode::getModeString() const {
    return "threaded";
}

bool ThreadedAudioMode::startAudioThread(EngineSimHandle handle, const EngineSimAPI& api,
                                         AudioPlayer* audioPlayer) {
    if (!audioPlayer) {
        return true;
    }
    
    EngineSimResult result = api.StartAudioThread(handle);
    if (result != ESIM_SUCCESS) {
        std::cerr << "ERROR: Failed to start audio thread\n";
        return false;
    }
    std::cout << "[Audio thread started (threaded mode)]\n";
    return true;
}

void ThreadedAudioMode::prepareBuffer(AudioPlayer* audioPlayer) {
    if (!audioPlayer) {
        return;
    }
    BufferOps::preFillCircularBuffer(audioPlayer);
    audioPlayer->start();
    std::cout << "[Audio playback enabled]\n";
}

void ThreadedAudioMode::resetBufferAfterWarmup(AudioPlayer* audioPlayer) {
    if (!audioPlayer) {
        return;
    }
    BufferOps::resetAndRePrefillBuffer(audioPlayer);
}

void ThreadedAudioMode::startPlayback(AudioPlayer* audioPlayer) {
    // Threaded mode: playback started in prepareBuffer
    (void)audioPlayer;
}

bool ThreadedAudioMode::shouldDrainDuringWarmup() const {
    // Threaded mode: draining needed during warmup
    return true;
}

// ============================================================================
// Factory Function
// ============================================================================

std::unique_ptr<IAudioMode> createAudioMode(bool syncPull) {
    if (syncPull) {
        return std::make_unique<SyncPullAudioMode>();
    }
    return std::make_unique<ThreadedAudioMode>();
}
